const Productdetail = [
  {
    id: 1,
    Title: 'Galaxy Tab S6 Lite 10.4 inch Android Tablet 128GB',
    Cat: 'Tablet',
    Price: '723',
    Img: './img/tp1.jpg',
  },
  {
    id: 2,
    Title: 'Galaxy Tab S6 Lite 10.4 inch Android Tablet 128GB',
    Cat: 'Smart Watch',
    Price: '723',
    Img: './img/tp2.jpg',
  },
  {
    id: 3,
    Title: 'Galaxy Tab S6 Lite 10.4 inch Android Tablet 128GB',
    Cat: 'Headphone',
    Price: '723',
    Img: './img/tp3.jpg',
  },
  {
    id: 4,
    Title: 'Galaxy Tab S6 Lite 10.4 inch Android Tablet 128GB',
    Cat: 'Headphone',
    Price: '723',
    Img: './img/tp4.jpg',
  },
  {
    id: 5,
    Title: 'Galaxy Tab S6 Lite 10.4 inch Android Tablet 128GB',
    Cat: 'Smart Watch',
    Price: '723',
    Img: './img/tp5.jpg',
  },
  {
    id: 6,
    Title: 'Galaxy Tab S6 Lite 10.4 inch Android Tablet 128GB',
    Cat: 'Book',
    Price: '723',
    Img: './img/tp6.png',
  },
  {
    id: 7,
    Title: 'Galaxy Tab S6 Lite 10.4 inch Android Tablet 128GB',
    Cat: 'Book',
    Price: '723',
    Img: './img/tp7.jpg',
  },
  {
    id: 8,
    Title: 'blabala .4 inch Android Tablet 128GB',
    Cat: 'Camera',
    Price: '723',
    Img: './img/tp8.jpg',
  },
  {
    id: 9,
    Title: 'stuff 128GB',
    Cat: 'Camera',
    Price: '723',
    Img: './img/p9.jpg',
  },
]
export default Productdetail;